// Generated by gencpp from file bug_algorithms/bugService.msg
// DO NOT EDIT!


#ifndef BUG_ALGORITHMS_MESSAGE_BUGSERVICE_H
#define BUG_ALGORITHMS_MESSAGE_BUGSERVICE_H

#include <ros/service_traits.h>


#include <bug_algorithms/bugServiceRequest.h>
#include <bug_algorithms/bugServiceResponse.h>


namespace bug_algorithms
{

struct bugService
{

typedef bugServiceRequest Request;
typedef bugServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bugService
} // namespace bug_algorithms


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bug_algorithms::bugService > {
  static const char* value()
  {
    return "c7f9b178e6a7aa0cd2e64b98d5c26b60";
  }

  static const char* value(const ::bug_algorithms::bugService&) { return value(); }
};

template<>
struct DataType< ::bug_algorithms::bugService > {
  static const char* value()
  {
    return "bug_algorithms/bugService";
  }

  static const char* value(const ::bug_algorithms::bugService&) { return value(); }
};


// service_traits::MD5Sum< ::bug_algorithms::bugServiceRequest> should match 
// service_traits::MD5Sum< ::bug_algorithms::bugService > 
template<>
struct MD5Sum< ::bug_algorithms::bugServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bug_algorithms::bugService >::value();
  }
  static const char* value(const ::bug_algorithms::bugServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bug_algorithms::bugServiceRequest> should match 
// service_traits::DataType< ::bug_algorithms::bugService > 
template<>
struct DataType< ::bug_algorithms::bugServiceRequest>
{
  static const char* value()
  {
    return DataType< ::bug_algorithms::bugService >::value();
  }
  static const char* value(const ::bug_algorithms::bugServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bug_algorithms::bugServiceResponse> should match 
// service_traits::MD5Sum< ::bug_algorithms::bugService > 
template<>
struct MD5Sum< ::bug_algorithms::bugServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bug_algorithms::bugService >::value();
  }
  static const char* value(const ::bug_algorithms::bugServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bug_algorithms::bugServiceResponse> should match 
// service_traits::DataType< ::bug_algorithms::bugService > 
template<>
struct DataType< ::bug_algorithms::bugServiceResponse>
{
  static const char* value()
  {
    return DataType< ::bug_algorithms::bugService >::value();
  }
  static const char* value(const ::bug_algorithms::bugServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUG_ALGORITHMS_MESSAGE_BUGSERVICE_H
