// Generated by gencpp from file principiante_tutoriales/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PRINCIPIANTE_TUTORIALES_MESSAGE_ADDTWOINTS_H
#define PRINCIPIANTE_TUTORIALES_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <principiante_tutoriales/AddTwoIntsRequest.h>
#include <principiante_tutoriales/AddTwoIntsResponse.h>


namespace principiante_tutoriales
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace principiante_tutoriales


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::principiante_tutoriales::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::principiante_tutoriales::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::principiante_tutoriales::AddTwoInts > {
  static const char* value()
  {
    return "principiante_tutoriales/AddTwoInts";
  }

  static const char* value(const ::principiante_tutoriales::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::principiante_tutoriales::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::principiante_tutoriales::AddTwoInts > 
template<>
struct MD5Sum< ::principiante_tutoriales::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::principiante_tutoriales::AddTwoInts >::value();
  }
  static const char* value(const ::principiante_tutoriales::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::principiante_tutoriales::AddTwoIntsRequest> should match 
// service_traits::DataType< ::principiante_tutoriales::AddTwoInts > 
template<>
struct DataType< ::principiante_tutoriales::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::principiante_tutoriales::AddTwoInts >::value();
  }
  static const char* value(const ::principiante_tutoriales::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::principiante_tutoriales::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::principiante_tutoriales::AddTwoInts > 
template<>
struct MD5Sum< ::principiante_tutoriales::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::principiante_tutoriales::AddTwoInts >::value();
  }
  static const char* value(const ::principiante_tutoriales::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::principiante_tutoriales::AddTwoIntsResponse> should match 
// service_traits::DataType< ::principiante_tutoriales::AddTwoInts > 
template<>
struct DataType< ::principiante_tutoriales::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::principiante_tutoriales::AddTwoInts >::value();
  }
  static const char* value(const ::principiante_tutoriales::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINCIPIANTE_TUTORIALES_MESSAGE_ADDTWOINTS_H
