(cl:defpackage bug_algorithms-srv
  (:use )
  (:export
   "BUGSERVICE"
   "<BUGSERVICE-REQUEST>"
   "BUGSERVICE-REQUEST"
   "<BUGSERVICE-RESPONSE>"
   "BUGSERVICE-RESPONSE"
   "BUGSWITCH"
   "<BUGSWITCH-REQUEST>"
   "BUGSWITCH-REQUEST"
   "<BUGSWITCH-RESPONSE>"
   "BUGSWITCH-RESPONSE"
  ))

