// Generated by gencpp from file bug_algorithms/bugSwitch.msg
// DO NOT EDIT!


#ifndef BUG_ALGORITHMS_MESSAGE_BUGSWITCH_H
#define BUG_ALGORITHMS_MESSAGE_BUGSWITCH_H

#include <ros/service_traits.h>


#include <bug_algorithms/bugSwitchRequest.h>
#include <bug_algorithms/bugSwitchResponse.h>


namespace bug_algorithms
{

struct bugSwitch
{

typedef bugSwitchRequest Request;
typedef bugSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bugSwitch
} // namespace bug_algorithms


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bug_algorithms::bugSwitch > {
  static const char* value()
  {
    return "06a69ed785453bce53ed290be7818f28";
  }

  static const char* value(const ::bug_algorithms::bugSwitch&) { return value(); }
};

template<>
struct DataType< ::bug_algorithms::bugSwitch > {
  static const char* value()
  {
    return "bug_algorithms/bugSwitch";
  }

  static const char* value(const ::bug_algorithms::bugSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::bug_algorithms::bugSwitchRequest> should match 
// service_traits::MD5Sum< ::bug_algorithms::bugSwitch > 
template<>
struct MD5Sum< ::bug_algorithms::bugSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bug_algorithms::bugSwitch >::value();
  }
  static const char* value(const ::bug_algorithms::bugSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bug_algorithms::bugSwitchRequest> should match 
// service_traits::DataType< ::bug_algorithms::bugSwitch > 
template<>
struct DataType< ::bug_algorithms::bugSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::bug_algorithms::bugSwitch >::value();
  }
  static const char* value(const ::bug_algorithms::bugSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bug_algorithms::bugSwitchResponse> should match 
// service_traits::MD5Sum< ::bug_algorithms::bugSwitch > 
template<>
struct MD5Sum< ::bug_algorithms::bugSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bug_algorithms::bugSwitch >::value();
  }
  static const char* value(const ::bug_algorithms::bugSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bug_algorithms::bugSwitchResponse> should match 
// service_traits::DataType< ::bug_algorithms::bugSwitch > 
template<>
struct DataType< ::bug_algorithms::bugSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::bug_algorithms::bugSwitch >::value();
  }
  static const char* value(const ::bug_algorithms::bugSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUG_ALGORITHMS_MESSAGE_BUGSWITCH_H
