// Generated by gencpp from file bug_algorithms/followAdvanceRequest.msg
// DO NOT EDIT!


#ifndef BUG_ALGORITHMS_MESSAGE_FOLLOWADVANCEREQUEST_H
#define BUG_ALGORITHMS_MESSAGE_FOLLOWADVANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bug_algorithms
{
template <class ContainerAllocator>
struct followAdvanceRequest_
{
  typedef followAdvanceRequest_<ContainerAllocator> Type;

  followAdvanceRequest_()
    : algorithm(0)
    , state(0)
    , reverse(false)
    , choose(false)  {
    }
  followAdvanceRequest_(const ContainerAllocator& _alloc)
    : algorithm(0)
    , state(0)
    , reverse(false)
    , choose(false)  {
  (void)_alloc;
    }



   typedef int32_t _algorithm_type;
  _algorithm_type algorithm;

   typedef int32_t _state_type;
  _state_type state;

   typedef uint8_t _reverse_type;
  _reverse_type reverse;

   typedef uint8_t _choose_type;
  _choose_type choose;





  typedef boost::shared_ptr< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct followAdvanceRequest_

typedef ::bug_algorithms::followAdvanceRequest_<std::allocator<void> > followAdvanceRequest;

typedef boost::shared_ptr< ::bug_algorithms::followAdvanceRequest > followAdvanceRequestPtr;
typedef boost::shared_ptr< ::bug_algorithms::followAdvanceRequest const> followAdvanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bug_algorithms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bug_algorithms': ['/home/mario/catkin_ws/src/bug_algorithms/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc69dfe3904d0c237938b0639fbc5a79";
  }

  static const char* value(const ::bug_algorithms::followAdvanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc69dfe3904d0c23ULL;
  static const uint64_t static_value2 = 0x7938b0639fbc5a79ULL;
};

template<class ContainerAllocator>
struct DataType< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bug_algorithms/followAdvanceRequest";
  }

  static const char* value(const ::bug_algorithms::followAdvanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 algorithm\n\
int32 state\n\
bool reverse\n\
bool choose\n\
";
  }

  static const char* value(const ::bug_algorithms::followAdvanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.algorithm);
      stream.next(m.state);
      stream.next(m.reverse);
      stream.next(m.choose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct followAdvanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bug_algorithms::followAdvanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bug_algorithms::followAdvanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "algorithm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.algorithm);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "reverse: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reverse);
    s << indent << "choose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.choose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUG_ALGORITHMS_MESSAGE_FOLLOWADVANCEREQUEST_H
