// Generated by gencpp from file bug_algorithms/followAdvance.msg
// DO NOT EDIT!


#ifndef BUG_ALGORITHMS_MESSAGE_FOLLOWADVANCE_H
#define BUG_ALGORITHMS_MESSAGE_FOLLOWADVANCE_H

#include <ros/service_traits.h>


#include <bug_algorithms/followAdvanceRequest.h>
#include <bug_algorithms/followAdvanceResponse.h>


namespace bug_algorithms
{

struct followAdvance
{

typedef followAdvanceRequest Request;
typedef followAdvanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct followAdvance
} // namespace bug_algorithms


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bug_algorithms::followAdvance > {
  static const char* value()
  {
    return "0cdc9d6762a3b9cb2474f738c3771c80";
  }

  static const char* value(const ::bug_algorithms::followAdvance&) { return value(); }
};

template<>
struct DataType< ::bug_algorithms::followAdvance > {
  static const char* value()
  {
    return "bug_algorithms/followAdvance";
  }

  static const char* value(const ::bug_algorithms::followAdvance&) { return value(); }
};


// service_traits::MD5Sum< ::bug_algorithms::followAdvanceRequest> should match 
// service_traits::MD5Sum< ::bug_algorithms::followAdvance > 
template<>
struct MD5Sum< ::bug_algorithms::followAdvanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bug_algorithms::followAdvance >::value();
  }
  static const char* value(const ::bug_algorithms::followAdvanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bug_algorithms::followAdvanceRequest> should match 
// service_traits::DataType< ::bug_algorithms::followAdvance > 
template<>
struct DataType< ::bug_algorithms::followAdvanceRequest>
{
  static const char* value()
  {
    return DataType< ::bug_algorithms::followAdvance >::value();
  }
  static const char* value(const ::bug_algorithms::followAdvanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bug_algorithms::followAdvanceResponse> should match 
// service_traits::MD5Sum< ::bug_algorithms::followAdvance > 
template<>
struct MD5Sum< ::bug_algorithms::followAdvanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bug_algorithms::followAdvance >::value();
  }
  static const char* value(const ::bug_algorithms::followAdvanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bug_algorithms::followAdvanceResponse> should match 
// service_traits::DataType< ::bug_algorithms::followAdvance > 
template<>
struct DataType< ::bug_algorithms::followAdvanceResponse>
{
  static const char* value()
  {
    return DataType< ::bug_algorithms::followAdvance >::value();
  }
  static const char* value(const ::bug_algorithms::followAdvanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUG_ALGORITHMS_MESSAGE_FOLLOWADVANCE_H
